# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wl0fXggN1tts1e1PWmBErFs90muunYfa
"""

!pip install numpy pandas scikit-learn

import numpy as np
import pandas as pd
from collections import deque

# Create sample dataset
np.random.seed(42)

data = {
    "feature1": np.random.rand(200),
    "feature2": np.random.rand(200),
    "feature3": np.random.rand(200),
    "label": np.random.randint(0, 2, 200)
}

df = pd.DataFrame(data)
df.to_csv("data.csv", index=False)

df.head()

class OnlineLogisticRegression:
    def __init__(self, learning_rate=0.01, n_features=3):
        self.lr = learning_rate
        self.weights = np.zeros(n_features)
        self.bias = 0

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def predict_proba(self, x):
        z = np.dot(x, self.weights) + self.bias
        return self.sigmoid(z)

    def predict(self, x):
        return 1 if self.predict_proba(x) >= 0.5 else 0

    def update(self, x, y):
        y_pred = self.predict_proba(x)
        error = y_pred - y

        # SGD update (learn from ONE row)
        self.weights -= self.lr * error * x
        self.bias -= self.lr * error

df = pd.read_csv("data.csv")

X = df.drop("label", axis=1).values
y = df["label"].values

X.shape, y.shape

model = OnlineLogisticRegression(
    learning_rate=0.01,
    n_features=X.shape[1]
)

for i in range(len(X)):
    prediction = model.predict(X[i])
    model.update(X[i], y[i])

    if i % 20 == 0:
        print(f"Row {i} | True: {y[i]} | Predicted: {prediction}")

window_size = 30
pred_window = deque(maxlen=window_size)
true_window = deque(maxlen=window_size)

for i in range(len(X)):
    pred = model.predict(X[i])
    model.update(X[i], y[i])

    pred_window.append(pred)
    true_window.append(y[i])

    if len(pred_window) == window_size:
        accuracy = np.mean(
            np.array(pred_window) == np.array(true_window)
        )
        print(f"Row {i} | Sliding Window Accuracy: {accuracy:.2f}")

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

batch_model = LogisticRegression()
batch_model.fit(X_train, y_train)

batch_preds = batch_model.predict(X_test)
print("Batch Model Accuracy:", accuracy_score(y_test, batch_preds))